# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "bootstrap"  
      - dependency-name: "chai"    
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/packages/api-stack" # Location of package manifests
    schedule:
      interval: "weekly" 
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/packages/api-tests" # Location of package manifests
    schedule:
      interval: "weekly" 
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/packages/chat" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "bootstrap"  
      - dependency-name: "chai"  
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/packages/lib" # Location of package manifests
    schedule:
      interval: "weekly"                                  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"