name = "vector_worker"
main = "src/worker.ts"
compatibility_date = "2024-01-10"
compatibility_flags = ["nodejs_compat"]

[[vectorize]]
binding = "VECTORIZE"
index_name = "tranmere-web-index"

[ai]
binding = "AI"

[vars]
CF_SPACE = ""
CF_KEY = ""