name = "tranmere-web"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"
pages_build_output_dir = ".vercel/output/static"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "tranmere-web"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "tranmere-web"
database_id = "cb021697-9af3-4872-b8eb-ce49be71bb8c"

[vars]
API_PORT="443" 
API_PROTOCOL="https"
API_DOMAIN="api.tranmere-web.com"
API_KEY=""