name: Api

on:
  push:
    branches: [ master ]
    paths:
      - 'packages/api-stack/**'
      - 'packages/lib/**'      
      - '.github/workflows/api.yml'   

permissions: read-all

jobs:
  build_test_and_package:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump.outputs.version }}
    permissions:
      contents: write     
    steps:
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.04
        with:
          node-version: '22.2.0'
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install
        run: yarn --frozen-lockfile
      - name: Unit Test
        run: yarn workspace @tranmere-web/api-stack test
        env:
          DD_KEY: ${{ secrets.DD_KEY }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
          CF_KEY: ${{ secrets.CF_KEY }}
      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@fdad52b3b3bbe8fad96b8ca18c56127a96f603db
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: bump
        run: echo "version=$(node tag.js)" >> $GITHUB_OUTPUT

  #trigger_web_deploy:
  #  runs-on: ubuntu-latest
  #  needs: build_test_and_package
  #  steps:
  #    - name: Call Web Hook
  #      run: curl -X POST https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/d244ae02-7152-4c32-b6c8-d75c023e735c       

  aws_cdk:
    runs-on: ubuntu-latest
    needs: build_test_and_package
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: '22.2.0'      
      - name: Install
        run: yarn --frozen-lockfile                 
      - name: Deploy CDK
        run: |
          yarn workspace @tranmere-web/api-stack cdk deploy --require-approval never "*"
        env:
          AWS_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
          CF_KEY: ${{ secrets.CF_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DD_TAGS: git.commit.sha:${{ github.sha }},git.repository_url:github.com/${{ github.repository }}

  data_dog:
    runs-on: ubuntu-latest
    needs: [build_test_and_package, aws_cdk]
    steps:
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: '22.2.0'    
      - name: Install Data Dog CI
        run: | 
          yarn global add @datadog/datadog-ci@${{ vars.DataDogCIVersion}}
      # https://docs.datadoghq.com/serverless/aws_lambda/installation/nodejs/?tab=awssam    
      - name: Instrument
        run: | 
          datadog-ci lambda instrument --functions-regex "^TranmereWebStack" -r eu-west-1 -v ${{ vars.DataDogNodeLayerVersion}} -e ${{ vars.DataDogExtensionLayerVersion}} --service tranmere-web --env prod --version ${{needs.build_test_and_package.outputs.version}} --merge-xray-traces false
        env:
          AWS_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DATADOG_API_KEY: ${{ secrets.DD_KEY }}
          DATADOG_SITE: datadoghq.eu

  api_acceptance_test:
    runs-on: ubuntu-latest
    needs: [aws_cdk, data_dog]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: '22.2.0'      
      - name: Post Deploy Checks
        run: 
          yarn workspace @tranmere-web/api-tests api

