name: Chat

on:
  push:
    branches: [ master ]  
    paths:
      - 'packages/chat/**'  
      - '.github/workflows/chat'   


jobs:
  chat_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/checkout@v4
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn workspace @tranmere-web/chat cloudflare-build      
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: tranmere-web-chatbot
          directory: ./packages/chat/.vercel/output/static
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
