name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build_test_and_package:
    runs-on: ubuntu-latest
    outputs:
      tag:
        ${{steps.tag_repo.outputs.new_tag}}
    steps:
      - uses: actions/checkout@v3
      - name: Install AWS CDK
        run: | 
          npm install -g aws-cdk
      - name: Install
        run: npm install
      - name: Unit Test
        run: npm run test
      - name: Bump version and push tag
        id: tag_repo
        uses: anothrNick/github-tag-action@1.55.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          WITH_V: true  
          RELEASE_BRANCHES: .* 
          INITIAL_VERSION: v1.0.1  
          AWS_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ENVIRONMENT: prod
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
          CF_KEY: ${{ secrets.CF_KEY }}
          SCRAPE_ID: ${{ secrets.SCRAPE_ID }}
          SCRAPE_SEASON: ${{ secrets.SCRAPE_SEASON }}
          SCRAPE_URL: ${{ secrets.SCRAPE_URL }}
          DD_KEY: ${{ secrets.DD_KEY }}

  aws_cdk:
    runs-on: ubuntu-latest
    steps:         
      - name: Deploy CDK
        run: |
          cdk deploy --require-approval never "*"
        env:
          AWS_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ENVIRONMENT: prod
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
          CF_KEY: ${{ secrets.CF_KEY }}
          SCRAPE_ID: ${{ secrets.SCRAPE_ID }}
          SCRAPE_SEASON: ${{ secrets.SCRAPE_SEASON }}
          SCRAPE_URL: ${{ secrets.SCRAPE_URL }}
          DD_KEY: ${{ secrets.DD_KEY }}
          VERSION: ${{needs.build_test_and_package.outputs.tag}}

  api_acceptance_test:
    runs-on: ubuntu-latest
    needs: aws_cdk
    steps:
      - name: Post Deploy Checks
        run: 
          newman run ./api_tests/postman-collection.json -e ./api_tests/env/aws-prod.json --env-var "testApiKey=${{ secrets.API_KEY }}"

  web_acceptance_test:
    runs-on: ubuntu-latest
    needs: aws_cdk
    steps:
      - name: Post Deploy Checks
        run: 
          newman run ./api_tests/postman-collection.json -e ./api_tests/env/cf-prod.json --env-var "testApiKey=${{ secrets.API_KEY }}"
