name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build_test_and_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install AWS CDK
        run: | 
          npm install -g aws-cdk
      - name: Install
        run: npm install
      - name: Unit Test
        run: npm run test
        env:
          DD_KEY: ${{ secrets.DD_KEY }}
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          

  trigger_web_deploy:
    runs-on: ubuntu-latest
    needs: build_test_and_package
    steps:
      - name: Call Web Hook
        run: curl -X POST https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/d244ae02-7152-4c32-b6c8-d75c023e735c       

  aws_cdk:
    runs-on: ubuntu-latest
    needs: build_test_and_package
    steps:
      - uses: actions/checkout@v3
      - name: Install AWS CDK
        run: | 
          npm install -g aws-cdk
      - name: Install
        run: npm install                   
      - name: Deploy CDK
        run: |
          cdk deploy --require-approval never "*"
        env:
          AWS_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ENVIRONMENT: prod
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
          CF_KEY: ${{ secrets.CF_KEY }}
          SCRAPE_ID: ${{ secrets.SCRAPE_ID }}
          SCRAPE_SEASON: ${{ secrets.SCRAPE_SEASON }}
          SCRAPE_URL: ${{ secrets.SCRAPE_URL }}
          DD_KEY: ${{ secrets.DD_KEY }}

  api_acceptance_test:
    runs-on: ubuntu-latest
    needs: aws_cdk
    steps:
      - uses: actions/checkout@v3
      - name: Install Newman
        run: | 
          npm install -g newman
      - name: Post Deploy Checks
        run: 
          newman run ./api_tests/postman-collection.json -e ./api_tests/env/aws-prod.json --env-var "testApiKey=${{ secrets.API_KEY }}"

  web_acceptance_test:
    runs-on: ubuntu-latest
    needs: aws_cdk
    steps:
      - uses: actions/checkout@v3
      - name: Install Newman
        run: | 
          npm install -g newman
      - name: Post Deploy Checks
        run: 
          newman run ./api_tests/postman-collection.json -e ./api_tests/env/cf-prod.json --env-var "testApiKey=${{ secrets.API_KEY }}"