name: Publish

on:
  push:
    branches: [ master ]
    paths:
      - 'tranmere-web/**'
      - 'functions/**'
      - 'templates/**'
      - '.github/workflows/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Run a build step here if your project requires
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
        env:
          CF_SPACE: ${{ secrets.CF_SPACE }}
          CF_KEY: ${{ secrets.CF_KEY }}
          API_KEY: ${{ secrets.API_KEY }}
          AL_KEY: ${{ secrets.AL_KEY }}
          AL_SPACE: ${{ secrets.AL_SPACE }}
          AL_INDEX: ${{ secrets.AL_INDEX }}
    #  - name: Install Wrangler App
    #    run: npm install wrangler
    #  - name: Create App
    #    run: npx wrangler pages project create tranmere-web --production-branch master
    #    continue-on-error: true
    #    env:
    #      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
    #      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: tranmere-web
          directory: web.out
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}