name: Pull Request Tests

on: [pull_request]

jobs:
  build_test_and_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install AWS CDK
        run: | 
          npm install -g aws-cdk
      - name: Install
        run: npm install
      - name: Unit Test
        run: npm run test
        env:
          DD_KEY: ${{ secrets.DD_KEY }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
          CF_KEY: ${{ secrets.CF_KEY }}