name: Pull Request Tests

on:
  pull_request:
    branches: [ "master" ]

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: '20'      
      - name: Install
        run: yarn --frozen-lockfile 
      - name: Unit Test
        run: npx lerna run test
        env:
          DD_KEY: ${{ secrets.DD_KEY }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
          CF_KEY: ${{ secrets.CF_KEY }}     
