name: Pull Request Tests

on:
  pull_request:
    branches: [ "master" ]

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: '20'      
      - name: Install
        run: yarn --frozen-lockfile 
      - name: Unit Test
        run: npx lerna run test
        env:
          DD_KEY: ${{ secrets.DD_KEY }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
          CF_KEY: ${{ secrets.CF_KEY }}     