name: Version Pull Request

on:
  pull_request:
    branches: [ "notused" ]

permissions: read-all

jobs:

  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf
        id: app-token
        with:
          app-id: ${{ vars.VERSION_BUMPER_APPID }}
          private-key: ${{ secrets.VERSION_BUMPER_SECRET }}      
      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@2d294fcd028d7ec0de2fa4e94ad7fe04512cc13a
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}