name: Web Deploy

on:
  push:
    branches: [ master ]
    paths:
      - 'packages/site/**'
      - '.github/workflows/web.yml'   

permissions: read-all

jobs:
  publish_site:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: '20'
      # Run a build step here if your project requires
      - name: Install
        run: yarn --frozen-lockfile 
      - name: Build
        run: yarn cloudflare-build
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CF_SPACE }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CF_KEY }}
          API_PORT: "443"
          API_PROTOCOL: "https" 
          API_DOMAIN: "api.tranmere-web.com"

      - uses: chrnorm/deployment-action@51e93982518dc06e500fe65559032a439663aaac
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          environment-url: https://www.tranmere-web.com
          environment: production
          description: "Pages Deployment"   

      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@b2a0191ce60d21388e1a8dcc968b4e9966f938e1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./packages/site
          command: pages deploy .vercel/output/static --project-name=tranmere-web

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806
        with:
          token: '${{ github.token }}'
          environment-url: ${{ steps.deploy.outputs.deployment-url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'success'          

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806
        with:
          token: '${{ github.token }}'
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'failure'          
