name: Web

on:
  push:
    branches: [ master ]
    paths:
      - 'packages/site/**'
      - '.github/workflows/web.yml'

permissions: read-all

jobs:
  publish_site:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: '20'
      # Run a build step here if your project requires
      - name: Install
        run: yarn --frozen-lockfile 
      - name: Build
        run: yarn cloudflare-build
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CF_SPACE }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CF_KEY }}
          API_PORT: "443"
          API_PROTOCOL: "https" 
          API_DOMAIN: "api.prod.tranmere-web.com"

      - name: Deploy
        uses: cloudflare/wrangler-action@9681c2997648301493e78cacbfb790a9f19c833f
        with:
          apiToken: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./packages/site
          command: pages deploy .vercel/output/static --project-name=tranmere-web

      #- uses: chrnorm/deployment-action@55729fcebec3d284f60f5bcabbd8376437d696b1
      #  name: Create GitHub deployment
      #  id: deployment
      #  with:
      #    token: '${{ secrets.GITHUB_TOKEN }}'
      #    environment-url: http://my-app-url.com
      #    environment: production   