name: Web

on:
  push:
    branches: [ master ]
    paths:
      - 'packages/site/**'
      - '.github/workflows/**'

jobs:
  publish_site:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      # Run a build step here if your project requires
      - name: Install
        run: yarn --frozen-lockfile 
      - name: Build
        run: yarn cloudflare-build
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CF_SPACE }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CF_KEY }}
          API_PORT: "443"
          API_PROTOCOL: "https" 
          API_DOMAIN: "api.prod.tranmere-web.com"

      - name: Build
        run: yarn cloudflare-deploy
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}