/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 47922a1cb9c7c48c675c384504394eaa)
interface __BaseEnv_Env {
  DB: D1Database;
  AUTH0_DOMAIN: 'dev-uy840dgvbfl4cef3.us.auth0.com';
  AUTH0_AUDIENCE: 'https://mcp.tranmere-web.com/mcp';
  API_BASE_URL: 'https://api.tranmere-web.com';
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/server');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, 'AUTH0_DOMAIN' | 'AUTH0_AUDIENCE' | 'API_BASE_URL'>
  > {}
}
