/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 650f97b57979bad3425b4e4ac738b6c4)
interface __BaseEnv_Env {
	DB: D1Database;
	AUTH0_DOMAIN: "dev-uy840dgvbfl4cef3.us.auth0.com";
	AUTH0_AUDIENCE: "https://mcp.tranmere-web.com/mcp";
	API_BASE_URL: "https://api.tranmere-web.com";
	MCP_WIDGET_DOMAIN: "https://mcp.tranmere-web.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH0_DOMAIN" | "AUTH0_AUDIENCE" | "API_BASE_URL" | "MCP_WIDGET_DOMAIN">> {}
}
