name = "tranmere-web-chatbot"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-01-10"
pages_build_output_dir = ".vercel/output/static"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "tranmere-web"

[ai]
binding = "AI"